// Generated by gencpp from file t3_description/goals.msg
// DO NOT EDIT!


#ifndef T3_DESCRIPTION_MESSAGE_GOALS_H
#define T3_DESCRIPTION_MESSAGE_GOALS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <t3_description/goal.h>

namespace t3_description
{
template <class ContainerAllocator>
struct goals_
{
  typedef goals_<ContainerAllocator> Type;

  goals_()
    : header()
    , goal_list()  {
    }
  goals_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::t3_description::goal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::t3_description::goal_<ContainerAllocator> >::other >  _goal_list_type;
  _goal_list_type goal_list;




  typedef boost::shared_ptr< ::t3_description::goals_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t3_description::goals_<ContainerAllocator> const> ConstPtr;

}; // struct goals_

typedef ::t3_description::goals_<std::allocator<void> > goals;

typedef boost::shared_ptr< ::t3_description::goals > goalsPtr;
typedef boost::shared_ptr< ::t3_description::goals const> goalsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t3_description::goals_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t3_description::goals_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace t3_description

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 't3_description': ['/home/t001/catkin_ws/src/t3_description/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::t3_description::goals_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t3_description::goals_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t3_description::goals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t3_description::goals_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t3_description::goals_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t3_description::goals_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t3_description::goals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acbe0f07c0aa4c7480edfbb28df6f816";
  }

  static const char* value(const ::t3_description::goals_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacbe0f07c0aa4c74ULL;
  static const uint64_t static_value2 = 0x80edfbb28df6f816ULL;
};

template<class ContainerAllocator>
struct DataType< ::t3_description::goals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t3_description/goals";
  }

  static const char* value(const ::t3_description::goals_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t3_description::goals_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
t3_description/goal[] goal_list\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: t3_description/goal\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::t3_description::goals_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t3_description::goals_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goals_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t3_description::goals_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t3_description::goals_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_list[]" << std::endl;
    for (size_t i = 0; i < v.goal_list.size(); ++i)
    {
      s << indent << "  goal_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::t3_description::goal_<ContainerAllocator> >::stream(s, indent + "    ", v.goal_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // T3_DESCRIPTION_MESSAGE_GOALS_H
