// Generated by gencpp from file imu_serial/imu_serial.msg
// DO NOT EDIT!


#ifndef IMU_SERIAL_MESSAGE_IMU_SERIAL_H
#define IMU_SERIAL_MESSAGE_IMU_SERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_serial
{
template <class ContainerAllocator>
struct imu_serial_
{
  typedef imu_serial_<ContainerAllocator> Type;

  imu_serial_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)  {
    }
  imu_serial_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;

   typedef float _gyro_x_type;
  _gyro_x_type gyro_x;

   typedef float _gyro_y_type;
  _gyro_y_type gyro_y;

   typedef float _gyro_z_type;
  _gyro_z_type gyro_z;




  typedef boost::shared_ptr< ::imu_serial::imu_serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_serial::imu_serial_<ContainerAllocator> const> ConstPtr;

}; // struct imu_serial_

typedef ::imu_serial::imu_serial_<std::allocator<void> > imu_serial;

typedef boost::shared_ptr< ::imu_serial::imu_serial > imu_serialPtr;
typedef boost::shared_ptr< ::imu_serial::imu_serial const> imu_serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_serial::imu_serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_serial::imu_serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'imu_serial': ['/home/t001/catkin_ws/src/imu_serial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_serial::imu_serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_serial::imu_serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_serial::imu_serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_serial::imu_serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_serial::imu_serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_serial::imu_serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_serial::imu_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "363773b161b4ac96d1ac5c46ff66e1df";
  }

  static const char* value(const ::imu_serial::imu_serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x363773b161b4ac96ULL;
  static const uint64_t static_value2 = 0xd1ac5c46ff66e1dfULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_serial::imu_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_serial/imu_serial";
  }

  static const char* value(const ::imu_serial::imu_serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_serial::imu_serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 acc_x\n\
float32 acc_y\n\
float32 acc_z\n\
float32 gyro_x\n\
float32 gyro_y\n\
float32 gyro_z\n\
";
  }

  static const char* value(const ::imu_serial::imu_serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_serial::imu_serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyro_x);
      stream.next(m.gyro_y);
      stream.next(m.gyro_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_serial::imu_serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_serial::imu_serial_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
    s << indent << "gyro_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyro_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_SERIAL_MESSAGE_IMU_SERIAL_H
